export const appStyles = {
  appContainer: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column' as const,
    padding: '24px',
    maxWidth: '1440px',
    margin: '0 auto',
    width: '100%',
  },
  header: {
    padding: '16px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
    flexWrap: 'wrap' as const,
    gap: '16px',
  },
  logoSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  logoIcon: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    background: 'rgba(143, 174, 147, 0.12)',
    border: '1px solid rgba(143, 174, 147, 0.28)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: 'none',
    overflow: 'hidden' as const,
  },
  logoText: {
    fontSize: '1.35rem',
    fontWeight: 800,
    letterSpacing: '-0.02em',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  badge: {
    fontSize: '0.75rem',
    fontWeight: 600,
    fontVariantNumeric: 'tabular-nums' as const,
    background: 'rgba(255, 255, 255, 0.08)',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    borderRadius: '6px',
    padding: '2px 6px',
    color: 'var(--text-secondary)',
  },
  logoSub: {
    fontSize: '0.8125rem',
    color: 'var(--text-secondary)',
    fontWeight: 500,
  },
  controlsSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  buttonGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  scanBtn: {
    padding: '10px 20px',
    fontSize: '0.9rem',
  },
  mainContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
  },
  errorBanner: {
    background: 'rgba(212, 134, 122, 0.12)',
    borderColor: 'rgba(212, 134, 122, 0.28)',
    padding: '12px 18px',
    borderRadius: '12px',
    marginBottom: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    color: 'var(--color-critical)',
    fontSize: '0.9rem',
    fontWeight: 500,
  },
  warnBanner: {
    background: 'rgba(212, 176, 122, 0.12)',
    borderColor: 'rgba(212, 176, 122, 0.28)',
    padding: '12px 18px',
    borderRadius: '12px',
    color: 'var(--color-warning)',
    fontSize: '0.9rem',
    fontWeight: 500,
    marginBottom: '20px',
  },
  closeBtn: {
    background: 'transparent',
    border: 'none',
    color: 'var(--color-critical)',
    cursor: 'pointer',
    fontSize: '1.2rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '4px',
  },
  scanningPanel: {
    padding: '28px',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'stretch',
    gap: '20px',
    marginBottom: '24px',
    borderStyle: 'dashed',
    borderColor: 'var(--accent)',
    animation: 'pulse-glow 2s infinite alternate',
  },
  scanHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  pulseIndicator: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: 'var(--accent)',
    boxShadow: 'none',
    animation: 'blink 1s infinite alternate',
  },
  scanMetrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '16px',
    background: 'rgba(255, 255, 255, 0.02)',
    padding: '16px',
    borderRadius: '12px',
    border: '1px solid rgba(255, 255, 255, 0.03)',
  },
  metricItem: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '4px',
  },
  metricLabel: {
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    fontWeight: 500,
  },
  metricVal: {
    fontSize: '1.25rem',
    fontWeight: 700,
  },
  scanningPath: {
    fontSize: '0.85rem',
    color: 'var(--text-secondary)',
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    background: 'rgba(0, 0, 0, 0.2)',
    padding: '8px 12px',
    borderRadius: '8px',
    border: '1px solid var(--border-color)',
  },
  welcomeGrid: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '24px',
    alignItems: 'stretch',
    marginTop: '20px',
  },
  welcomeCard: {
    padding: '48px 36px',
    textAlign: 'center' as const,
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '20px',
  },
  welcomeTitle: {
    fontSize: '2rem',
    fontWeight: 800,
    letterSpacing: '-0.02em',
  },
  welcomeSubtitle: {
    fontSize: '1rem',
    color: 'var(--text-secondary)',
    maxWidth: '700px',
    lineHeight: '1.6',
  },
  supportAlert: {
    background: 'rgba(143, 174, 147, 0.1)',
    border: '1px solid rgba(143, 174, 147, 0.22)',
    borderRadius: '12px',
    padding: '12px 20px',
    fontSize: '0.875rem',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    maxWidth: '800px',
    textAlign: 'left' as const,
    lineHeight: '1.5',
  },
  actionCenter: {
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    gap: '12px',
    marginTop: '16px',
  },
  hugeBtn: {
    padding: '16px 36px',
    fontSize: '1.1rem',
    borderRadius: '16px',
  },
  securityHint: {
    fontSize: '0.8rem',
    color: 'var(--text-secondary)',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  featureCards: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '24px',
  },
  featureCard: {
    padding: '24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '12px',
  },
  dashboard: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '20px',
  },
  tabsContainer: {
    display: 'flex',
    padding: '6px',
    borderRadius: '12px',
    gap: '8px',
  },
  tabItem: {
    flex: 1,
    padding: '12px',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: '0.9rem',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8px',
    transition: 'all 0.2s ease',
  },
  tabContent: {
    flex: 1,
  },
  footer: {
    marginTop: '40px',
    borderTop: '1px solid var(--border-color)',
    paddingTop: '20px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '12px',
    fontSize: '0.8rem',
    color: 'var(--text-muted)',
    flexWrap: 'wrap' as const,
  },
};
